# Copyright 2026 Serge Rabyking
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
# The receive-proof bitstream: dvi2rgb front end, two capture paths.
# Batch: vivado -mode batch -source build.tcl (from /work in the container)
set here [file dirname [file normalize [info script]]]
set root [file normalize [file join $here .. ..]]
set_param board.repoPaths [file join $root board-files]

# EVERY number this script needs comes from here, and this script owns
# none of them. params.tcl is generated by gen/params.py from the three
# files that do own them: the design (gen/pipeline.json), the target
# (board.json) and the ISP's own traced contract. There are no defaults
# below and no environment reads: a fact that is missing stops the build
# here, rather than becoming a width mismatch that Vivado downgrades to
# a warning and a picture that is quietly wrong.
if {![file exists [file join $here generated params.tcl]]} {
    error "bd.tcl: boards/<board>/generated/params.tcl is missing. It is generated\
 by gen/params.py, after the ISP -- because the ISP's boundary is traced\
 rather than declared. Run build.sh rather than this script alone."
}
source [file join $here generated params.tcl]

create_project rx [file join $here build rx] -part $p_part -force
set_property board_part $p_board_part [current_project]
set_property ip_repo_paths [file join $root vivado-library] [current_project]
update_ip_catalog

add_files [file join $root hdl generated scanout.v] \
    [file join $root hdl generated grab_fifo.v] \
    [file join $root hdl link_reset.v] [file join $root hdl stream_switch.v] [file join $root hdl axis_unpack.v] \
    [file join $root hdl isp_axis.v] [file join $root hdl isp_shim.v] \
    [file join $root hdl generated revela_isp_core.v] \
    [file join $root hdl generated isp_tee.v] [file join $root hdl generated isp_skid.v] [file join $root hdl tee_shim.v] [file join $root hdl axis_pick.v] \
    [file join $root hdl generated ddc_slave.v] [file join $root hdl ddc_phy.v] \
    [file join $root hdl generated bayerlink_rx.v] \
    [file join $root hdl rx_axis.v] [file join $root hdl vid_probe.v] \
    [file join $root hdl axis_spy.v]
add_files -fileset constrs_1 [file join $here pynq-z2.xdc]

create_bd_design rx

# --- PS, with the board preset; HP0 for both DMAs; 200 MHz for IDELAYCTRL
set ps [create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7 ps7]
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \
    -config {make_external "FIXED_IO, DDR" apply_board_preset "1"} $ps
set_property -dict [list \
    CONFIG.PCW_USE_S_AXI_HP0 {1} \
    CONFIG.PCW_USE_S_AXI_HP1 {0} \
    CONFIG.PCW_EN_CLK1_PORT {1} \
    CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ $p_ps_clk_mhz \
    CONFIG.PCW_FPGA1_PERIPHERAL_FREQMHZ {200} \
    CONFIG.PCW_USE_FABRIC_INTERRUPT {1} \
    CONFIG.PCW_IRQ_F2P_INTR {1}] $ps
# FCLK0 (every AXI clock here) at 142.86, not 100: a 1080p60 scanout
# READS 497 MB/s sustained, and a 64-bit HP port at 100 MHz peaks at
# 800 -- close enough to the edge that the raster starves and the
# display path spends its life re-hunting the frame start. The PS can
# make 1000/7; it cannot make 150.

# --- TMDS decode
set dvi [create_bd_cell -type ip -vlnv digilentinc.com:ip:dvi2rgb dvi_rx]
# kClkRange 1: the board's own base overlay runs this exact 74.25 MHz
# mode with range 1 -- the IP comment's bucket arithmetic says 2, and
# empirically range 2 locks the clock but never aligns the data. Trust
# the design that demonstrably receives.
# DDC no longer belongs to dvi2rgb: the receiver answers for itself.
# Its canned EDID was a borrowed 720p monitor identity; the ddc_slave
# below serves our OWN EDID (preferred timing = the container,
# 1920x1081@30) at 0x50 and the ISP's register file at 0x37, on the
# same two wires. One engine, and the cable becomes the control plane.
set_property -dict [list CONFIG.kClkRange {1} CONFIG.kEmulateDDC {false} \
    CONFIG.kAddBUFG {true}] $dvi
make_bd_intf_pins_external [get_bd_intf_pins dvi_rx/TMDS]
set_property name TMDS [get_bd_intf_ports TMDS_0]
connect_bd_net [get_bd_pins ps7/FCLK_CLK1] [get_bd_pins dvi_rx/RefClk]

# HPD high: the Pi must see a sink.
set one [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant hpd_one]
create_bd_port -dir O hdmi_hpd
connect_bd_net [get_bd_pins hpd_one/dout] [get_bd_ports hdmi_hpd]

# dvi2rgb wants a reset; not held in reset when locked
set rstinv [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant rst_lo]
set_property CONFIG.CONST_VAL {0} $rstinv
connect_bd_net [get_bd_pins rst_lo/dout] [get_bd_pins dvi_rx/aRst]

# --- the framebuffer writer: the ISP's output lands here
set vdma [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_vdma vdma]
set_property -dict [list CONFIG.c_include_mm2s {0} CONFIG.c_include_s2mm {1} \
    CONFIG.c_s_axis_s2mm_tdata_width {32} \
    CONFIG.c_s2mm_linebuffer_depth {2048}] $vdma

# --- R2 path: the unpacked line stream to DDR
#
# The sample width. The receiver ALIGNS every source depth to the depth
# this build was made for, so one number describes the whole datapath
# from its output to the ISP's input, and the glue is parameterised on
# it rather than assuming a 16-bit lane. build.sh owns it and exports
# it. There is NO default: the depth has one owner, the design
# description, and build.sh reads it from there and exports it. A
# fallback here would be a second owner -- and the failure it produces
# is not an error but a picture that is quietly wrong, which is the
# worst kind. Refuse instead.
set sample_bits $p_sample_bits

# BUILD-TIME, like the sample width, and the second of its kind here.
# The CAPTURE branch writes received frames to DDR so the ARM can judge
# them against what the camera sent -- the tap that proved this link
# bit-exact. It costs a DMA, a clock converter, an interconnect port
# and the switch that exists only because there are two consumers, so a
# build that is not being brought up should be able to leave it out.
# Whether the board CAN is board business (it needs the PS and an HP
# port); whether this build DOES is build.sh's. build.sh resolves the
# two and exports the answer.
set capture $p_capture
# The display has ONE source: the ISP stream, direct, genlocked.
# Memory is not a display source -- it is a GRABBER, an instrument
# software points at an address and switches on. Conflating the two
# is what once dragged in triple buffering, a rotation thread, and a
# supervisor: machinery for rate-adapting a display that the clock
# steering does better in 24 ps steps. Latency to glass is lines,
# always -- there is no mode with a frame store in the picture path.
#
# The output raster's pixel clock, stated by the build (build.sh
# derives it from the mode table, the one owner). A 74.25-class raster
# rides a SECOND output of the same MMCM -- 742.5 VCO / 10, exact --
# and GENLOCKS to the stream; a 148.5-class raster keeps the island's
# clock and free-runs.
set out_mhz $p_out_mhz
set genlock_en $p_genlock
# the genlock clock groups ride a separate PLAIN xdc: strict XDC has
# no `if`, and a skipped guard once timed the async crossing at 6 ps
if {$genlock_en} {
    add_files -fileset constrs_1 [file join $here genlock-clocks.xdc]
}
# Coefficients are LIVE, always: np2hw's AXI4-Lite register file,
# whose writes land in a shadow and commit at a frame boundary. The
# baked-constants variant retired once this path was proven -- the
# operating model is NEUTRAL at power-on, calibration restored over
# the cable by whoever holds the sensor's profile.
puts "bd.tcl: output $out_mhz MHz[expr {$genlock_en ? { genlocked} : {}}], coefficients live"
puts "bd.tcl: sample width $sample_bits bits, capture path $capture"
puts "bd.tcl: the ISP under test is $p_isp_toplevel -- $sample_bits-bit\
 in, $p_isp_out_bits-bit out ($p_isp_channels x $p_isp_chan_bits),\
 latency $p_isp_latency px"
# --- the pixel datapath: GENERATED.
# Which blocks carry the stream, what width each is built at, and the
# wires between them come from boards/<board>/design.json via
# gen/netlist.py, with every width checked against the modules' own
# ports before this file is reached. What stays here is everything that
# is NOT a stream edge: clocks, resets, vendor IP and the AXI
# automation -- the parts where a declarative model would be a worse
# version of something that already works.
source [file join $here generated netlist.tcl]
connect_bd_net [get_bd_pins dvi_rx/PixelClk] [get_bd_pins blrx/clk]
foreach {a b} {vid_pData vid_data vid_pVDE vid_de vid_pVSync vid_vsync} {
    connect_bd_net [get_bd_pins dvi_rx/$a] [get_bd_pins blrx/$b]
}
# One stream, two consumers, a register deciding which: the judge's
# byte-exact capture, or the ISP. The unselected side sees silence.
# With capture, one stream has two consumers and a register picks; the
# ISP then reads the switch's B side. Without it there is one consumer,
# so there is no switch, no select bit, and the ISP reads the receiver.
# `isp_src` is whichever of the two the ISP branch is wired from.
if {$capture} {
    connect_bd_net [get_bd_pins dvi_rx/PixelClk] [get_bd_pins shim/clk]
}
# THE ISLAND CLOCK. Genlocked builds: FCLK0 directly -- the 148.5
# exactness was the one-clock display era's requirement and died
# when the display got its own MMCM; the island only needs to be
# faster than the stream's average and of board ancestry, and
# 142.86 is both. This retires a fractional MMCM, merges the island
# with the PS-AXI domain (their converters go with it), and gives
# the week's most timing-pressed logic 4% more period for free.
# Legacy free-running builds keep the old 148.5 MMCM, island and
# display as one clock, exactly as before.
if {$genlock_en} {
    set islck ps7/FCLK_CLK0
    set lk1 [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant lock_hi]
    set_property -dict [list CONFIG.CONST_WIDTH {1} CONFIG.CONST_VAL {1}] $lk1
    set isllock lock_hi/dout
} else {
    set islck clk_out/clk_out1
    set isllock clk_out/locked
    set cw [create_bd_cell -type ip -vlnv xilinx.com:ip:clk_wiz clk_out]
    # No_buffer: FCLK arrives from the PS already buffered; the default
    # expects a package PIN and builds an input path to nowhere -- an MMCM
    # that never sees an edge, and a perfectly silent dead clock.
    # Fed from FCLK1 (200 MHz), not FCLK0: the AXI clock moved to 1000/7
    # for scanout bandwidth, and 142.86 cannot synthesize an exact 148.5
    # (the nearest fractional divide lands 0.24% low). 200 x 3.7125 =
    # 742.5 VCO, /5 = 148.5 exactly -- the same VCO the 74.25 recipe used.
    set_property -dict [list CONFIG.PRIM_IN_FREQ {200.000} \
        CONFIG.PRIM_SOURCE {No_buffer} \
        CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {148.500} \
        CONFIG.USE_LOCKED {true} CONFIG.USE_RESET {false}] $cw
    connect_bd_net [get_bd_pins ps7/FCLK_CLK1] [get_bd_pins clk_out/clk_in1]
}

if {$genlock_en} {
    # The raster's own MMCM -- not a second output of the island's.
    # The genlock steers this clock through the FINE PHASE SHIFTER
    # (~24 ps a step, cumulative: a fractional frequency trim), and
    # the steering must provably touch NOTHING but the display
    # domain. Same recipe as the island's: 200/10 x 37.125 = the
    # 742.5 VCO, /10 = 74.25 exact; the PS step is VCO/56 = 24.05 ps,
    # which is where the generator's 560 steps-per-pixel comes from.
    # PSCLK is the output itself: legal, and the stepper inside
    # scanout is then simply in its own domain.
    set cw74 [create_bd_cell -type ip -vlnv xilinx.com:ip:clk_wiz clk_out74]
    # The recipe is FORCED, not requested: asked for 74.250 the wizard
    # optimizes jitter and lands 74.287 (490 ppm off, past the steering
    # authority); asked politely with a second output it lands 74.242.
    # OVERRIDE_MMCM states the primitive outright: 200/10 x 37.125 =
    # the 742.5 VCO, /10 = 74.25 EXACT -- and the fine phase step is
    # pinned with it (742.5/56 = 24.05 ps; the generator's 560
    # steps-per-pixel is a fact about THIS recipe).
    set_property -dict [list CONFIG.PRIM_IN_FREQ {200.000} \
        CONFIG.PRIM_SOURCE {No_buffer} \
        CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {74.250} \
        CONFIG.USE_DYN_PHASE_SHIFT {true} \
        CONFIG.USE_LOCKED {true} CONFIG.USE_RESET {false} \
        CONFIG.OVERRIDE_MMCM {true} \
        CONFIG.MMCM_DIVCLK_DIVIDE {10} \
        CONFIG.MMCM_CLKFBOUT_MULT_F {37.125} \
        CONFIG.MMCM_CLKOUT0_DIVIDE_F {10.000} \
        CONFIG.CLK_OUT1_USE_FINE_PS_GUI {true} \
        CONFIG.MMCM_CLKOUT0_USE_FINE_PS {true}] $cw74
    # the line above is the entire genlock: USE_FINE_PS defaults FALSE
    # even with the phase-shift interface enabled, and a stepper whose
    # steps land on a deaf output is dead reckoning with a 2-second
    # jam cycle -- exactly what the first glass test showed
    connect_bd_net [get_bd_pins ps7/FCLK_CLK1] [get_bd_pins clk_out74/clk_in1]
    connect_bd_net [get_bd_pins clk_out74/clk_out1] [get_bd_pins clk_out74/psclk]
}

# --- the ISP branch, an island on the BOARD'S OWN clock.
#
# This island existed once, retired when np2hw closed timing on the
# receiver's clock, and is back for a reason that has nothing to do
# with timing: the receiver's clock is recovered from the cable, so it
# STOPS -- on unplug, and in the moments after the fabric is
# reprogrammed. Everything that lived on it inherited that: an AXI
# slave there hung the processor (power cycle, 2026-08-17), the
# register file fled to the PS clock, and every coefficient became a
# clock crossing with constraints in both directions.
#
# clk_out1 is 148.5MHz from FCLK_CLK1 -- no cable anywhere in its
# ancestry -- and the scanout already runs on it. With the ISP and its
# register file BOTH there, the coefficient crossing does not need
# constraining, arming, or explaining: it is gone. One stream crossing
# remains, in the converter below, proven vendor IP doing the one job.
#
# The pieces are the ORIGINAL island's: rx_axis dresses the elastic
# stream as AXIS, the converter crosses, axis_unpack undresses it.
# One layout, owned by rx_axis, both directions.
connect_bd_net [get_bd_pins dvi_rx/PixelClk] [get_bd_pins isp_in_shim/clk]
set icdc [create_bd_cell -type ip -vlnv xilinx.com:ip:axis_clock_converter isp_cdc]
connect_bd_intf_net [get_bd_intf_pins isp_in_shim/m_axis] [get_bd_intf_pins isp_cdc/S_AXIS]
connect_bd_net [get_bd_pins dvi_rx/PixelClk]  [get_bd_pins isp_cdc/s_axis_aclk]
connect_bd_net [get_bd_pins $islck] [get_bd_pins isp_cdc/m_axis_aclk]
connect_bd_net [get_bd_pins $islck] [get_bd_pins isp_unpack/clk]
connect_bd_intf_net [get_bd_intf_pins isp_cdc/M_AXIS] [get_bd_intf_pins isp_unpack/s_axis]
connect_bd_net [get_bd_pins $islck] [get_bd_pins isp/clk]
# The stream's own facts drive the pipeline context: header to ctx,
# one owner end to end. This is now a REAL clock crossing -- pixel
# domain to the island -- and it is safe for the same reason it always
# was: the values change at header-accept, a full line before the
# payload, and the wrapper latches them at each frame's SOF, by which
# time they have been still for thousands of cycles. The XDC says so.
foreach f {width height phase bits} {
    connect_bd_net [get_bd_pins blrx/hdr_$f] [get_bd_pins isp/hdr_$f]
}

# --- the output TEE: one ISP stream, two switchable consumers.
# Branch B stores (VDMA -> framebuffer), branch A goes DIRECT to the
# scanout. Off means DISCARD at the tee -- both off and the pipeline
# still runs, which is what standby statistics will stand on -- and
# switching is frame-atomic inside the tee, so neither consumer ever
# receives a partial frame.
#
# The DIRECT branch is whole when the raster is genlocked: the
# scanout follows the stream's rate and phase, so fps flows through
# and no store intervenes -- line latency through the board. On a
# free-running build it remains what it always was: the mechanism and
# the honest failure (scanout refuses between frames), with the
# framebuffer as the rate adapter.
connect_bd_net [get_bd_pins $islck] [get_bd_pins isp_tee/clk]
connect_bd_net [get_bd_pins $islck] [get_bd_pins isp_out/clk]
connect_bd_intf_net [get_bd_intf_pins isp_out/m_axis] [get_bd_intf_pins vdma/S_AXIS_S2MM]
# The direct branch, dressed the same way for the same sink dialect.
connect_bd_net [get_bd_pins $islck] [get_bd_pins isp_dir/clk]
if {$capture} {
set cdc [create_bd_cell -type ip -vlnv xilinx.com:ip:axis_clock_converter cdc]
connect_bd_intf_net [get_bd_intf_pins shim/m_axis] [get_bd_intf_pins cdc/S_AXIS]
connect_bd_net [get_bd_pins dvi_rx/PixelClk] [get_bd_pins cdc/s_axis_aclk]

set dma [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_dma dma]
# 32-bit words: the v2 receiver's samples are 16-bit unshifted, plus
# sof/eol above them (rx_axis owns the layout).
set_property -dict [list CONFIG.c_include_mm2s {0} CONFIG.c_include_sg {0} \
    CONFIG.c_s_axis_s2mm_tdata_width {32} CONFIG.c_sg_length_width {26}] $dma
set spy [create_bd_cell -type module -reference axis_spy spy_cdc]
set_property -dict [list CONFIG.DW {32}] $spy
connect_bd_net [get_bd_pins ps7/FCLK_CLK0] [get_bd_pins spy_cdc/clk]
connect_bd_intf_net [get_bd_intf_pins cdc/M_AXIS] [get_bd_intf_pins spy_cdc/s_axis]
connect_bd_intf_net [get_bd_intf_pins spy_cdc/m_axis] [get_bd_intf_pins dma/S_AXIS_S2MM]
}

# --- display side. Pixel clock is OURS (the board's MMCM, never the
# cable's); rgb2dvi makes its own 5x serial clock (MMCM: 742.5 sits
# inside the MMCM VCO window; a PLL's floor is above it). clk_out is
# created up with the receiver: the ISP island uses it before the
# display side does. A genlocked build puts the raster on clk_out2
# (74.25) and slaves its rate and phase to the stream; a free-running
# build keeps it on the island's 148.5.
# the display pixel clock: the steerable MMCM's when genlocked,
# the island's when free-running
if {$genlock_en} {
    set pixq clk_out74
} else {
    set pixq clk_out
}

# No v_tc, no v_axi4s_vid_out: that pair's lock was never witnessed
# here across every mode it offers. The raster is GENERATED -- np2hw's
# scanout, emitted from the one raster table, arriving with the claims
# this bench paid for: a frame may be dropped but never displaced, a
# window that does not fit is refused rather than clipped, and pixel
# and enable leave on the same clock. Placement is a run-time fact
# and arrives on registers, whose file is placed below -- on the bus
# clock, not the cable's.
set tx [create_bd_cell -type ip -vlnv digilentinc.com:ip:rgb2dvi hdmi_tx]
# kClkRange picks the serializer MMCM's multiplier bucket (MULT_F =
# range*5, from the IP source): 1 covers >=120 MHz (148.5 x 5 = 742.5
# VCO), 2 covers >=60 (74.25 x 10 = the same 742.5 VCO).
# PLL, not MMCM: a fixed x5 with no phase steering is the PLL's
# whole job (integer math exact: 74.25 -> VCO 1113.75 /3; 148.5 ->
# VCO 1485 /2), and it hands an MMCM back to the budget.
set_property -dict [list CONFIG.kGenerateSerialClk {true} \
    CONFIG.kClkPrimitive {PLL} \
    CONFIG.kClkRange [expr {$out_mhz >= 120 ? 1 : 2}] \
    CONFIG.kRstActiveHigh {true}] $tx
set vp [create_bd_cell -type module -reference scanout_top scanout]
connect_bd_net [get_bd_pins $pixq/clk_out1] [get_bd_pins scanout/clk]
connect_bd_net [get_bd_pins $pixq/locked] [get_bd_pins scanout/locked]
connect_bd_intf_net [get_bd_intf_pins scanout/vid_io] [get_bd_intf_pins hdmi_tx/RGB]
connect_bd_net [get_bd_pins $pixq/clk_out1] [get_bd_pins hdmi_tx/PixelClk]
if {$genlock_en} {
    # the steering wires: the raster asks, the MMCM steps, PSDONE
    # answers -- all in the display domain
    connect_bd_net [get_bd_pins scanout/ps_en] [get_bd_pins clk_out74/psen]
    connect_bd_net [get_bd_pins scanout/ps_incdec] [get_bd_pins clk_out74/psincdec]
    connect_bd_net [get_bd_pins clk_out74/psdone] [get_bd_pins scanout/ps_done]
}
make_bd_intf_pins_external [get_bd_intf_pins hdmi_tx/TMDS]
set_property name hdmi_tx [get_bd_intf_ports TMDS_0]

# The scanout's source is the ISP direct branch, and nothing else.
# The tee upstream switches frame-atomically and scanout re-anchors
# on tuser, so enabling or disabling the picture costs a frame,
# never a hang; with the branch off or the source gone, the raster
# free-runs and paints fill -- the TV never loses sync.
if {$genlock_en} {
    # The island-to-raster crossing: np2hw's gray-pointer FIFO, 8192
    # deep -- the genlock's lead is STORAGE, and this is where it
    # lives. Both faces reset by the broom: pointers that reset on one
    # side only disagree forever after, and the broom is already the
    # raster's own restart.
    set ocdc [create_bd_cell -type module -reference out_cdc out_cdc]
    connect_bd_net [get_bd_pins $islck] [get_bd_pins out_cdc/wclk]
    connect_bd_net [get_bd_pins clk_out74/clk_out1] [get_bd_pins out_cdc/rclk]
    connect_bd_intf_net [get_bd_intf_pins isp_dir/m_axis] [get_bd_intf_pins out_cdc/s_axis]
    connect_bd_intf_net [get_bd_intf_pins out_cdc/m_axis] [get_bd_intf_pins scanout/s_axis]
} else {
    connect_bd_intf_net [get_bd_intf_pins isp_dir/m_axis] [get_bd_intf_pins scanout/s_axis]
}

# The VDMA is the GRABBER: write side only, capturing frames to an
# address software chose, for software to judge -- so software
# owning its buffering, its re-arming and its races is proper. The
# display never depends on it: grabbing on, off, halted or torn,
# the picture is the direct branch's and stays whole.
# ONE frame store, stated: the grabber is a single-buffer instrument
# by contract (software owns any fancier buffering), and a store
# register nobody programmed is ADDRESS ZERO -- an engine built with
# three stores visited it (DMAIntErr, frames toward low DDR).
set_property -dict [list CONFIG.c_include_mm2s {0} \
    CONFIG.c_use_fsync {0} \
    CONFIG.c_num_fstores {1} \
    CONFIG.c_s2mm_genlock_mode {0}] $vdma

# --- interrupts: the pynq drivers refuse to exist without them
set irqcat [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconcat irq_cat]
connect_bd_net [get_bd_pins vdma/s2mm_introut] [get_bd_pins irq_cat/In0]
if {$capture} {
    connect_bd_net [get_bd_pins dma/s2mm_introut] [get_bd_pins irq_cat/In1]
} else {
    # Same vector shape either way, so the driver's view does not move.
    set irq0 [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant irq_tie]
    set_property -dict [list CONFIG.CONST_WIDTH {1} CONFIG.CONST_VAL {0}] $irq0
    connect_bd_net [get_bd_pins irq_tie/dout] [get_bd_pins irq_cat/In1]
}
connect_bd_net [get_bd_pins irq_cat/dout] [get_bd_pins ps7/IRQ_F2P]

# --- software reset for the receiver: a sticky overflow needs a broom
set ctrl [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio ctrl_gpio]
# Channel 2 is reserved (it once carried a read engine's base
# address; the grabber's addresses go through the VDMA's own
# registers). Software bits: broom(0), consumer select(1),
# unused(2), GRAB enable(3), DIRECT enable(4). The output enables
# are quasi-static and honoured by the tee at frame boundaries only,
# so a write here changes the picture a frame later and never tears
# it.
# POWER-ON DEFAULTS say what the board IS: consumer = ISP (bit 1)
# and the direct picture enabled (bit 4). A freshly programmed board
# shows the camera with no software running at all -- the board is a
# bitstream; scripts are visitors. Grab (bit 3) defaults off, so the
# write engine never touches memory nobody allocated.
set_property -dict [list CONFIG.C_GPIO_WIDTH {5} CONFIG.C_ALL_OUTPUTS {1} \
    CONFIG.C_DOUT_DEFAULT {0x00000012} \
    CONFIG.C_IS_DUAL {1} CONFIG.C_GPIO2_WIDTH {32} \
    CONFIG.C_ALL_OUTPUTS_2 {1}] $ctrl
# Bit 0 is the broom, bit 1 selects the stream's consumer (judge/ISP).
set brm [create_bd_cell -type ip -vlnv xilinx.com:ip:xlslice broom]
set_property -dict [list CONFIG.DIN_WIDTH {5} CONFIG.DIN_FROM {0} \
    CONFIG.DIN_TO {0}] $brm
connect_bd_net [get_bd_pins ctrl_gpio/gpio_io_o] [get_bd_pins broom/Din]
# The tee's enables: quasi-static software bits, sampled by the tee at
# frame boundaries only, crossing on the wholesale ctrl_gpio false path.
set osl [create_bd_cell -type ip -vlnv xilinx.com:ip:xlslice o_grab]
set_property -dict [list CONFIG.DIN_WIDTH {5} CONFIG.DIN_FROM {3} \
    CONFIG.DIN_TO {3}] $osl
connect_bd_net [get_bd_pins ctrl_gpio/gpio_io_o] [get_bd_pins o_grab/Din]
connect_bd_net [get_bd_pins o_grab/Dout] [get_bd_pins isp_tee/en_b]
set odl [create_bd_cell -type ip -vlnv xilinx.com:ip:xlslice o_direct]
set_property -dict [list CONFIG.DIN_WIDTH {5} CONFIG.DIN_FROM {4} \
    CONFIG.DIN_TO {4}] $odl
connect_bd_net [get_bd_pins ctrl_gpio/gpio_io_o] [get_bd_pins o_direct/Din]
connect_bd_net [get_bd_pins o_direct/Dout] [get_bd_pins isp_tee/en_a]
if {$genlock_en} {
    # ONE bit means the picture AND the law: direct enabled means
    # the raster follows its stream; direct off means there is
    # nothing to follow and the raster free-runs the mode.
    connect_bd_net -net [get_bd_nets -of_objects [get_bd_pins isp_tee/en_a]] \
        [get_bd_pins scanout/param_follow]
    # The crossing resets with the raster: the broom is the raster's
    # restart, and gray pointers that reset on one side only disagree
    # forever after. Both faces, one broom. Plain form: broom/Dout has
    # no net yet at this point in the script -- this connect creates
    # it, and the later broom connects extend it.
    connect_bd_net [get_bd_pins broom/Dout] \
        [get_bd_pins out_cdc/wrst] [get_bd_pins out_cdc/rrst]
}

# The pixel domain's reset comes from the LINK, not from a person.
# That domain runs on the clock recovered from the cable, so an unplug
# stops it: FIFOs freeze half full, the ISP mid-line, the writer mid
# frame. Nothing in there can notice, which is why a replug used to
# need a register poke. The supervisor runs on FCLK0, which cannot
# stop, asserts asynchronously so it lands with no pixel clock at all,
# and releases synchronously so the domain leaves reset on an edge.
# Power-up needs no special case: no lock, so the domain is held until
# a source appears. The broom still overrides, for a stuck sticky bit.
set lrst [create_bd_cell -type module -reference link_reset link_rst]
connect_bd_net [get_bd_pins ps7/FCLK_CLK0]      [get_bd_pins link_rst/stable_clk]
connect_bd_net [get_bd_pins dvi_rx/PixelClk]    [get_bd_pins link_rst/pix_clk]
connect_bd_net [get_bd_pins dvi_rx/aPixelClkLckd] [get_bd_pins link_rst/locked_a]
connect_bd_net [get_bd_pins broom/Dout]         [get_bd_pins link_rst/soft_rst]
# Bit 1 chooses the stream's consumer, which is only a choice when
# there are two of them. Without capture the ISP is the only consumer
# and the bit means nothing, so the slice is not built; bit 0, the
# broom, is unaffected and keeps its meaning either way.
if {$capture} {
    set msel [create_bd_cell -type ip -vlnv xilinx.com:ip:xlslice isp_sel]
    set_property -dict [list CONFIG.DIN_WIDTH {5} CONFIG.DIN_FROM {1} \
        CONFIG.DIN_TO {1}] $msel
    connect_bd_net [get_bd_pins ctrl_gpio/gpio_io_o] [get_bd_pins isp_sel/Din]
    connect_bd_net [get_bd_pins isp_sel/Dout] [get_bd_pins sw/sel]
}
# The island still FOLLOWS the link -- a half-frame left in the pipe
# by an unplug is cleared the same way as before -- but through a
# reset of its own, because rst_pix deasserts synchronously to a clock
# the island does not use. proc_sys_reset re-synchronises the release
# to clk_out1, and holds until the MMCM locks, which is what makes
# power-up need no special case. Instantiated HERE, explicitly, with
# an input whose state software can read (link_up in hdr_gpio) -- not
# left to the automation, whose hidden resets cost three builds once.
#
# The register file is deliberately NOT in this reset: it rides
# s_axil_aresetn, so coefficients survive a cable pull, and the
# datapath reloads its copies the moment its own reset releases.
set irst [create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset rst_isp]
connect_bd_net [get_bd_pins $islck]  [get_bd_pins rst_isp/slowest_sync_clk]
connect_bd_net [get_bd_pins link_rst/rst_pix]  [get_bd_pins rst_isp/ext_reset_in]
connect_bd_net [get_bd_pins $isllock]    [get_bd_pins rst_isp/dcm_locked]
foreach cell {isp isp_out isp_unpack isp_tee isp_dir} {
    connect_bd_net [get_bd_pins rst_isp/peripheral_reset] [get_bd_pins $cell/rst]
}
connect_bd_net [get_bd_pins rst_isp/peripheral_aresetn] \
    [get_bd_pins isp_cdc/m_axis_aresetn]
# The converter's pixel side follows the link directly, like the shim
# feeding it: both are IN the pixel domain, where rst_pix is the law.
set rlk [create_bd_cell -type ip -vlnv xilinx.com:ip:util_vector_logic rstn_link]
set_property -dict [list CONFIG.C_SIZE {1} CONFIG.C_OPERATION {not}] $rlk
connect_bd_net [get_bd_pins link_rst/rst_pix] [get_bd_pins rstn_link/Op1]
connect_bd_net [get_bd_pins rstn_link/Res]    [get_bd_pins isp_cdc/s_axis_aresetn]
connect_bd_net [get_bd_pins link_rst/rst_pix] [get_bd_pins isp_in_shim/rst]
connect_bd_net [get_bd_pins link_rst/rst_pix] [get_bd_pins blrx/rst]
# The tallies clear on a deliberate ask, not on every cable drop: rst
# now arrives from the LINK, and a counter reset by the event it counts
# tells you nothing. The broom is a person saying "start again".
connect_bd_net [get_bd_pins broom/Dout] [get_bd_pins blrx/diag_clear]
if {$capture} {
    catch {connect_bd_net [get_bd_pins link_rst/rst_pix] [get_bd_pins shim/rst]}
}

# --- status: lock + overflow + the probe's testimony
set probe [create_bd_cell -type module -reference vid_probe probe]
connect_bd_net [get_bd_pins dvi_rx/PixelClk] [get_bd_pins probe/clk]
connect_bd_net [get_bd_pins link_rst/rst_pix] [get_bd_pins probe/rst]
connect_bd_net [get_bd_pins dvi_rx/vid_pVDE] [get_bd_pins probe/de]
connect_bd_net [get_bd_pins dvi_rx/vid_pVSync] [get_bd_pins probe/vsync]
connect_bd_net [get_bd_pins dvi_rx/vid_pData] [get_bd_pins probe/data]
connect_bd_net [get_bd_pins blrx/out_valid] [get_bd_pins probe/rx_valid]

set gpio [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio status_gpio]
set_property -dict [list CONFIG.C_GPIO_WIDTH {30} CONFIG.C_ALL_INPUTS {1} \
    CONFIG.C_IS_DUAL {1} CONFIG.C_GPIO2_WIDTH {32} CONFIG.C_ALL_INPUTS_2 {1}] $gpio
if {$capture} {
    connect_bd_net [get_bd_pins broom/Dout] [get_bd_pins spy_cdc/rst]
}
set cat2 [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconcat status2_cat]
set_property CONFIG.NUM_PORTS {3} $cat2
if {$capture} {
    connect_bd_net [get_bd_pins spy_cdc/status] [get_bd_pins status2_cat/In0]
} else {
    # The spy's 16 status bits read zero rather than moving every other
    # field in the word: a host reading this register keeps its offsets.
    set spy0 [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant spy_tie]
    set_property -dict [list CONFIG.CONST_WIDTH {16} CONFIG.CONST_VAL {0}] $spy0
    connect_bd_net [get_bd_pins spy_tie/dout] [get_bd_pins status2_cat/In0]
}
if {$genlock_en} {
    connect_bd_net [get_bd_pins clk_out74/locked] [get_bd_pins status2_cat/In1]
} else {
    connect_bd_net [get_bd_pins clk_out/locked] [get_bd_pins status2_cat/In1]
}
connect_bd_net [get_bd_pins scanout/status] [get_bd_pins status2_cat/In2]
connect_bd_net [get_bd_pins status2_cat/dout] [get_bd_pins status_gpio/gpio2_io_i]
# The v2 receiver's verdicts and header facts, packed for one read:
# {hdr_phase[1:0], hdr_valid, hdr_bits[4:0], refuse_code[2:0], refused}
set hcat [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconcat hdr_cat]
set_property CONFIG.NUM_PORTS {5} $hcat
connect_bd_net [get_bd_pins blrx/refused] [get_bd_pins hdr_cat/In0]
connect_bd_net [get_bd_pins blrx/refuse_code] [get_bd_pins hdr_cat/In1]
connect_bd_net [get_bd_pins blrx/hdr_bits] [get_bd_pins hdr_cat/In2]
connect_bd_net [get_bd_pins blrx/hdr_valid] [get_bd_pins hdr_cat/In3]
connect_bd_net [get_bd_pins blrx/hdr_phase] [get_bd_pins hdr_cat/In4]
# The island must say WHY it is idle. Held in reset, starved by the
# converter, refusing input and producing nothing all look identical
# from software -- no data, no error -- and telling those apart by
# guesswork cost a day once. Six levels, sampled raw across the
# clock boundary: these are read as LEVELS for stuck-at diagnosis, not
# as events, so the crossing needs no synchroniser to be useful.
#   bit2 island reset held    bit3 stream reaching the ISP
#   bit4 ISP accepting        bit5 ISP producing
#   bit6 pixel side offering  bit7 pixel side accepted
# These taps join EXISTING nets, so every one uses the -net form; the
# plain form errors on a pin that is already connected.
set islcat [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconcat isl_cat]
set_property CONFIG.NUM_PORTS {7} $islcat
connect_bd_net -net [get_bd_nets -of_objects [get_bd_pins rst_isp/peripheral_reset]] \
    [get_bd_pins isl_cat/In0]
connect_bd_net -net [get_bd_nets -of_objects [get_bd_pins isp/in_valid]] \
    [get_bd_pins isl_cat/In1]
connect_bd_net -net [get_bd_nets -of_objects [get_bd_pins isp/in_ready]] \
    [get_bd_pins isl_cat/In2]
connect_bd_net -net [get_bd_nets -of_objects [get_bd_pins isp/out_valid]] \
    [get_bd_pins isl_cat/In3]
connect_bd_net -net [get_bd_nets -of_objects [get_bd_pins isp_in_shim/in_valid]] \
    [get_bd_pins isl_cat/In4]
connect_bd_net -net [get_bd_nets -of_objects [get_bd_pins isp_in_shim/in_ready]] \
    [get_bd_pins isl_cat/In5]
# Pad to the 16 bits the probe used to occupy, so the header facts
# stay at bit 18 and every host script keeps its offsets.
set islpad [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant isl_pad]
set_property -dict [list CONFIG.CONST_WIDTH {10} CONFIG.CONST_VAL {0}] $islpad
connect_bd_net [get_bd_pins isl_pad/dout] [get_bd_pins isl_cat/In6]

set cat [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconcat status_cat]
set_property CONFIG.NUM_PORTS {4} $cat
connect_bd_net [get_bd_pins dvi_rx/aPixelClkLckd] [get_bd_pins status_cat/In0]
connect_bd_net [get_bd_pins blrx/overflow] [get_bd_pins status_cat/In1]
connect_bd_net [get_bd_pins isl_cat/dout] [get_bd_pins status_cat/In2]
connect_bd_net [get_bd_pins hdr_cat/dout] [get_bd_pins status_cat/In3]

# --- WHICH frame, and WHICH camera. Both status words are full to the
# bit, and these do not belong crammed into a spare corner anyway: they
# are the stream's identity. Software reads them to recognise a source
# and load ITS calibration, and to tell a frame the link LOST from one
# the camera never sent.
#
# OBSERVABILITY, not correlation. This reports the LAST ACCEPTED
# header -- the frame ENTERING the pipeline. By the time a frame's
# statistics are ready the next header has landed and this has moved
# on, so statistics must carry their OWN frame id, latched with the
# accumulators in one snapshot. Reading this beside a separate stats
# register is a race with a one-frame error, which is what makes an
# exposure loop oscillate.
set hgpio [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio hdr_gpio]
# Channel 2 carries 8 + 8 + 1 + 8 + 1 + 1 of fact and 5 of pad: 32.
# A wider channel would leave its top bits unconnected, which Vivado
# reports and which reads back as whatever the fabric felt like.
set_property -dict [list CONFIG.C_GPIO_WIDTH {32} CONFIG.C_ALL_INPUTS {1} \
    CONFIG.C_IS_DUAL {1} CONFIG.C_GPIO2_WIDTH {32} \
    CONFIG.C_ALL_INPUTS_2 {1}] $hgpio
connect_bd_net [get_bd_pins blrx/hdr_frame_seq] [get_bd_pins hdr_gpio/gpio_io_i]
# Channel 2 is the stream's identity plus the link's own testimony.
# The layout, low bits first, and it is the ONE statement of it -- a
# second one drifted for as long as this file described a word with
# fb_slverr and fb_underflow in it, two signals that stopped existing
# when the read engine was retired:
#
#   [7:0]   source_id      which camera sent it
#   [15:8]  resync_count   stream restarts, wrapping
#   [16]    link_up        settled lock
#   [24:17] loss_count     link drops seen, wrapping
#   [25]    torn_a         display branch fell behind
#   [26]    torn_b         grabber fell behind
#   [31:27] zero           pad to the GPIO's width
#
# A host polls this one word and knows what is connected, whether the
# cable has dropped since it last looked, and whether the stream
# restarted -- all as COUNTS, so a poll that misses an event still
# sees that it happened.
set icat [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconcat ident_cat]
set_property CONFIG.NUM_PORTS {7} $icat
connect_bd_net [get_bd_pins blrx/hdr_source_id]  [get_bd_pins ident_cat/In0]
connect_bd_net [get_bd_pins blrx/resync_count]   [get_bd_pins ident_cat/In1]
connect_bd_net [get_bd_pins link_rst/link_up]    [get_bd_pins ident_cat/In2]
connect_bd_net [get_bd_pins link_rst/loss_count] [get_bd_pins ident_cat/In3]
# The retired read engine's two status slots now carry the tee's
# torn stickies -- same offsets, honest new meaning: a branch that
# fell behind lost ITS OWN beats (the tee never stalls; a consumer's
# death is private). torn_a = display branch, torn_b = grabber.
connect_bd_net [get_bd_pins isp_tee/torn_a] [get_bd_pins ident_cat/In4]
connect_bd_net [get_bd_pins isp_tee/torn_b] [get_bd_pins ident_cat/In5]
# The pad is exactly what is left of the 32, and no more. At 8 bits --
# a leftover placeholder from the retired read engine -- the word came
# to 35 and the block design dropped three bits with a CRITICAL
# WARNING on every build. Those three were constant zeros, so nothing
# was ever lost; the cost was that a REAL width mistake in this word
# would have printed the identical message next to the one everybody
# had learned to scroll past.
set fbz8 [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant fb_dbg0]
set_property -dict [list CONFIG.CONST_WIDTH {5} CONFIG.CONST_VAL {0}] $fbz8
connect_bd_net [get_bd_pins fb_dbg0/dout] [get_bd_pins ident_cat/In6]
connect_bd_net [get_bd_pins ident_cat/dout] [get_bd_pins hdr_gpio/gpio2_io_i]
connect_bd_net [get_bd_pins status_cat/dout] [get_bd_pins status_gpio/gpio_io_i]

# --- automation for AXI plumbing, resets, address map
#
# The bus's own reset exists BEFORE any automation runs: released
# once the PS is up, deliberately blind to the link. History twice
# over -- the automation, offered a domain where the only
# proc_sys_reset was the link's (rst_isp), borrowed it for the bus:
# first for the register file (2026-08-17, power cycle), then again
# the day the island joined FCLK0 and rst_isp entered the bus
# domain's field of view (caught by checkhwh before it could hang
# anything). The sweep after the automations makes the choice
# deterministic regardless of what the automation prefers.
set brst [create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset rst_bus]
connect_bd_net [get_bd_pins $islck]  [get_bd_pins rst_bus/slowest_sync_clk]
connect_bd_net [get_bd_pins ps7/FCLK_RESET0_N] [get_bd_pins rst_bus/ext_reset_in]
connect_bd_net [get_bd_pins $isllock] [get_bd_pins rst_bus/dcm_locked]
apply_bd_automation -rule xilinx.com:bd_rule:axi4 -config \
    {Clk_master {Auto} Clk_slave {Auto} Clk_xbar {Auto} Master {/ps7/M_AXI_GP0} intc_ip {New AXI Interconnect}} \
    [get_bd_intf_pins vdma/S_AXI_LITE]
if {$capture} {
apply_bd_automation -rule xilinx.com:bd_rule:axi4 -config \
    {Clk_master {Auto} Clk_slave {Auto} Clk_xbar {Auto} Master {/ps7/M_AXI_GP0} intc_ip {New AXI Interconnect}} \
    [get_bd_intf_pins dma/S_AXI_LITE]
}
apply_bd_automation -rule xilinx.com:bd_rule:axi4 -config \
    {Clk_master {Auto} Clk_slave {Auto} Clk_xbar {Auto} Master {/ps7/M_AXI_GP0} intc_ip {New AXI Interconnect}} \
    [get_bd_intf_pins status_gpio/S_AXI]
apply_bd_automation -rule xilinx.com:bd_rule:axi4 -config \
    {Clk_master {Auto} Clk_slave {Auto} Clk_xbar {Auto} Master {/ps7/M_AXI_GP0} intc_ip {New AXI Interconnect}} \
    [get_bd_intf_pins hdr_gpio/S_AXI]
# Every coefficient behind one slave, ON THE PROCESSOR'S CLOCK.
#
# It rode the PIXEL clock once. That clock is recovered from the
# HDMI link and stops with it, including in the moments just after
# this bitstream is loaded -- and AXI has no timeout, so a slave
# with no clock never answers and the processor waits for it
# forever. The board hung on 2026-08-17 and needed the power pulled.
#
# Clk_slave is NAMED rather than left to Auto. Auto picked the pixel
# clock, correctly, because the wrapper's interface association said
# that is where the port lived; the fix is in the wrapper, and this
# says the same thing out loud so the two cannot drift apart.
# Master and slave on one clock also means no clock converter.
# ...and on the ISLAND's clock, which is the whole point: the
# register file and the datapath that reads it share a domain, so
# the coefficient crossing that needed an arm for safety and false
# paths in both directions simply does not exist.
#
# But NOT the island's RESET. The island follows the link; the bus
# must not. The first build of this let the automation choose the
# crossing's reset, and it grabbed the only proc_sys_reset in the
# domain -- rst_isp, the link's -- so a cable pull held the
# register file's arready at zero and the next read of 0x40000000
# hung the processor. The same lesson as the pixel-clocked slave,
# one level up: last time a CLOCK that stopped with the cable,
# this time a RESET held by it. Anything a host can reach must
# answer, and that means its clock AND its reset answer to the
# board, not to the cable.
#
# So nothing here is left for the automation to guess: the bus
# gets its own reset (rst_bus -- released once the PS is up and
# the MMCM locks, deliberately blind to the link), and the clock
# converter is placed EXPLICITLY, every clock and reset named.
# The automation is only ever handed the FCLK0 side, where there
# is nothing cross-domain left to decide.
connect_bd_net [get_bd_pins $islck]   [get_bd_pins isp/s_axi_aclk]
# The regfile's reset pin is CONNECTED BEFORE the automation runs,
# because a pin already taken is a pin the automation leaves alone.
connect_bd_net [get_bd_pins rst_bus/peripheral_aresetn] [get_bd_pins isp/s_axi_aresetn]
apply_bd_automation -rule xilinx.com:bd_rule:axi4 -config \
    [expr {$genlock_en
        ? {Clk_master {/ps7/FCLK_CLK0} Clk_slave {/ps7/FCLK_CLK0} Clk_xbar {/ps7/FCLK_CLK0} Master {/ps7/M_AXI_GP0} intc_ip {New AXI Interconnect}}
        : {Clk_master {/ps7/FCLK_CLK0} Clk_slave {/clk_out/clk_out1} Clk_xbar {/ps7/FCLK_CLK0} Master {/ps7/M_AXI_GP0} intc_ip {New AXI Interconnect}}}] \
    [get_bd_intf_pins isp/s_axi]
# ...and then its choices are REPAIRED, because the automation also
# picks a reset for the interconnect port it creates in the island
# clock domain, and it picks whatever proc_sys_reset it likes the
# look of. The wedging build had M03_ARESETN on rst_isp: the
# crossing coupler itself held in reset by the link, so even a
# regfile with a sound reset sat behind a dead port. Every pin the
# automation put on the link's reset moves to the bus's, and the
# build REFUSES if any survives -- this is a correctness invariant,
# not a preference.
set busnet [get_bd_nets -of_objects [get_bd_pins rst_bus/peripheral_aresetn]]
foreach pin [get_bd_pins -quiet ps7_axi_periph/*ARESETN*] {
    set n [get_bd_nets -quiet -of_objects $pin]
    if {$n ne "" && [string match "*rst_isp*" [get_property NAME $n]]} {
        disconnect_bd_net $n $pin
        connect_bd_net -net $busnet $pin
        puts "bd.tcl: moved $pin off the link's reset"
    }
}
foreach pin [get_bd_pins -quiet ps7_axi_periph/*ARESETN*] {
    set n [get_bd_nets -quiet -of_objects $pin]
    if {$n ne "" && [string match "*rst_isp*" [get_property NAME $n]]} {
        error "bd.tcl: $pin still rides the link's reset -- a cable\
 pull would hold the bus port in reset and hang the processor"
    }
}

# --- placement's register file, on the same terms.
# The scanout's datapath runs on the cable's recovered clock, but its
# register file does NOT: it runs here, on the bus clock, for exactly
# the reason written above. The values cross into the pixel domain
# behind an arm/acknowledge handshake, one bit each way, so an absent
# pixel clock costs a placement update and never the bus.
#
# Same discipline as the ISP's, and for the same bench-paid reason:
# both pins connected BEFORE the automation runs, so there is nothing
# cross-domain left for it to choose.
connect_bd_net [get_bd_pins $islck] [get_bd_pins scanout/s_axi_aclk]
connect_bd_net [get_bd_pins rst_bus/peripheral_aresetn] \
    [get_bd_pins scanout/s_axi_aresetn]
apply_bd_automation -rule xilinx.com:bd_rule:axi4 -config \
    [expr {$genlock_en
        ? {Clk_master {/ps7/FCLK_CLK0} Clk_slave {/ps7/FCLK_CLK0} Clk_xbar {/ps7/FCLK_CLK0} Master {/ps7/M_AXI_GP0} intc_ip {Auto}}
        : {Clk_master {/ps7/FCLK_CLK0} Clk_slave {/clk_out/clk_out1} Clk_xbar {/ps7/FCLK_CLK0} Master {/ps7/M_AXI_GP0} intc_ip {Auto}}}] \
    [get_bd_intf_pins scanout/s_axi]
# The same repair, because the same automation makes the same choice
# again for the port it just created. The invariant is checked once,
# below, over every port on the interconnect -- including this one.
foreach pin [get_bd_pins -quiet ps7_axi_periph/*ARESETN*] {
    set n [get_bd_nets -quiet -of_objects $pin]
    if {$n ne "" && [string match "*rst_isp*" [get_property NAME $n]]} {
        disconnect_bd_net $n $pin
        connect_bd_net -net $busnet $pin
        puts "bd.tcl: moved $pin off the link's reset"
    }
}
foreach pin [get_bd_pins -quiet ps7_axi_periph/*ARESETN*] {
    set n [get_bd_nets -quiet -of_objects $pin]
    if {$n ne "" && [string match "*rst_isp*" [get_property NAME $n]]} {
        error "bd.tcl: $pin still rides the link's reset -- a cable\
 pull would hold the bus port in reset and hang the processor"
    }
}

# --- the DDC slave: the register file, reachable over the cable.
# A second master wants isp/s_axi, so a 2x1 interconnect goes in
# front of it -- single-clock (everything here lives on the bus
# clock) and single-reset (the bus's own; the coupler IS the path,
# and a held coupler hangs exactly like a held slave). Wired
# explicitly, nothing left for automation to guess.
set dphy [create_bd_cell -type module -reference ddc_phy ddc_phy]
set dslv [create_bd_cell -type module -reference ddc_slave ddc]
connect_bd_net [get_bd_pins ddc_phy/scl_i] [get_bd_pins ddc/scl_i]
connect_bd_net [get_bd_pins ddc_phy/sda_i] [get_bd_pins ddc/sda_i]
connect_bd_net [get_bd_pins ddc/sda_pull] [get_bd_pins ddc_phy/sda_pull]
connect_bd_net [get_bd_pins $islck] [get_bd_pins ddc/clk]
# rst is declared ACTIVE_HIGH at its owner; peripheral_reset is
# the matching output of the bus's generator.
connect_bd_net [get_bd_pins rst_bus/peripheral_reset] [get_bd_pins ddc/rst]
create_bd_port -dir I ddc_scl_io
connect_bd_net [get_bd_ports ddc_scl_io] [get_bd_pins ddc_phy/scl_io]
create_bd_port -dir IO ddc_sda_io
connect_bd_net [get_bd_ports ddc_sda_io] [get_bd_pins ddc_phy/sda_io]

set ispnet [get_bd_intf_nets -of_objects [get_bd_intf_pins isp/s_axi]]
set mpin ""
foreach ip [get_bd_intf_pins -of_objects $ispnet] {
    if {$ip ne [get_bd_intf_pins isp/s_axi]} { set mpin $ip }
}
if {$mpin eq ""} { error "bd.tcl: no master found feeding isp/s_axi" }
delete_bd_objs $ispnet
set icd [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect ic_ddc]
set_property -dict [list CONFIG.NUM_SI {2} CONFIG.NUM_MI {1}] $icd
connect_bd_intf_net $mpin [get_bd_intf_pins ic_ddc/S00_AXI]
connect_bd_intf_net [get_bd_intf_pins ddc/M_AXI] [get_bd_intf_pins ic_ddc/S01_AXI]
connect_bd_intf_net [get_bd_intf_pins ic_ddc/M00_AXI] [get_bd_intf_pins isp/s_axi]
foreach c {ACLK S00_ACLK S01_ACLK M00_ACLK} {
    connect_bd_net [get_bd_pins $islck] [get_bd_pins ic_ddc/$c]
}
foreach r {ARESETN S00_ARESETN S01_ARESETN M00_ARESETN} {
    connect_bd_net -net $busnet [get_bd_pins ic_ddc/$r]
}
assign_bd_address -target_address_space /ddc/M_AXI \
    [get_bd_addr_segs isp/s_axi/reg0] -offset 0x00000000 -range 32K
apply_bd_automation -rule xilinx.com:bd_rule:axi4 -config \
    {Clk_master {Auto} Clk_slave {Auto} Clk_xbar {Auto} Master {/ps7/M_AXI_GP0} intc_ip {New AXI Interconnect}} \
    [get_bd_intf_pins ctrl_gpio/S_AXI]
apply_bd_automation -rule xilinx.com:bd_rule:axi4 -config \
    {Clk_master {Auto} Clk_slave {Auto} Clk_xbar {Auto} Master {/vdma/M_AXI_S2MM} \
     Slave {/ps7/S_AXI_HP0} ddr_seg {Auto} intc_ip {New AXI Interconnect} master_apm {0}} \
    [get_bd_intf_pins ps7/S_AXI_HP0]
# NOT automation: its second pass built the dma a private interconnect
# whose master port went to __NOC__ -- nowhere -- and called it a
# warning. The capture engines share this interconnect, explicitly.
# Two masters write DDR when capture is in: the grabber and the
# capture DMA. Without it the grabber is alone and the second
# slave port is not created at all. Nothing READS the DDR in the
# picture path anymore -- the display is direct -- so the read
# bandwidth argument and the port it justified are both gone.
if {$capture} {
    set_property CONFIG.NUM_SI {2} [get_bd_cells axi_mem_intercon]
}
# The automation's reset generator for this clock has the MMCM's lock on
# dcm_locked already -- checked in the .xci, not assumed. Its
# ext_reset_in and aux_reset_in are left unconnected, which the block
# design ties to 0, and whether 0 means "reset" depends on a polarity
# nobody stated. State it: with both ACTIVE_HIGH, a tied-off 0 is
# unambiguously "not asserted", and this generator releases after its
# power-on sequence instead of possibly never.
# A relic with a live lesson: before the one-clock move, fbread's
# display clock was a domain the automation had not seen, so it
# generated a reset for it -- whose unstated polarity was the
# island-held-in-reset bug's cousin, fixed here by declaration.
# With everything AXI on the board's one clock the automation reuses
# the existing resets and generates NOTHING, so the cell to fix
# may not exist -- and an audit that errors on its absence would
# refuse exactly the builds that no longer have the problem.
set rc [get_bd_cells -quiet rst_clk_out_148M]
if {$rc ne ""} {
    set_property -dict [list CONFIG.C_EXT_RST_ACTIVE_HIGH {1} \
        CONFIG.C_AUX_RST_ACTIVE_HIGH {1}] $rc
} else {
    puts "bd.tcl: no automation reset generator to repair (one clock)"
}
if {$capture} {
connect_bd_intf_net [get_bd_intf_pins dma/M_AXI_S2MM] \
    [get_bd_intf_pins axi_mem_intercon/S01_AXI]
connect_bd_net [get_bd_pins ps7/FCLK_CLK0] [get_bd_pins axi_mem_intercon/S01_ACLK]
connect_bd_net [get_bd_pins ps7/FCLK_CLK0] [get_bd_pins dma/m_axi_s2mm_aclk]
connect_bd_net -net [get_bd_nets -of_objects [get_bd_pins axi_mem_intercon/S00_ARESETN]] \
    [get_bd_pins axi_mem_intercon/S01_ARESETN]
}
# Stream-side clocks the automation does not own: everything AXI in
# this design lives on FCLK0, so the crossings are exactly the two
# declared ones (TMDS pixel clock in, FCLK0 out).
# The write side follows the ISP onto the island: producer and
# consumer on one clock, no converter, and a clock that keeps running
# through an unplug -- the engine can now finish or fault a frame
# instead of freezing mid-word when the cable goes.
connect_bd_net [get_bd_pins $islck] [get_bd_pins vdma/s_axis_s2mm_aclk]
# `cdc` belongs to the capture branch, so this belongs inside the same
# guard. Left outside it, CAPTURE=0 -- a configuration this repo
# documents and build.sh offers -- failed to build at all.
if {$capture} {
    connect_bd_net [get_bd_pins ps7/FCLK_CLK0] [get_bd_pins cdc/m_axis_aclk]
}

# RESETS the automation does not own. A floating aresetn is a HELD
# reset -- the clock converter and video-in have sat in reset through
# every test so far. AXI-side resetns join the net the automation
# gives the DMA; the converter's pixel-side resetn is the software
# reset, inverted, so one broom sweeps the whole receive path.
set inv [create_bd_cell -type ip -vlnv xilinx.com:ip:util_vector_logic rstn_pix]
set_property -dict [list CONFIG.C_SIZE {1} CONFIG.C_OPERATION {not}] $inv
connect_bd_net [get_bd_pins broom/Dout] [get_bd_pins rstn_pix/Op1]
# An async-FIFO crossing initializes only when BOTH sides reset while
# BOTH clocks run. At boot the pixel clock does not exist, so boot-time
# resets can never do it. The RECEIVE path no longer depends on anyone
# noticing: link_rst holds it until lock settles, which is by
# definition a moment when both clocks run. This converter belongs to
# the capture branch and keeps the broom, which is honest -- it is a
# bring-up path, and it is brought up by hand.
if {$capture} {
    connect_bd_net [get_bd_pins rstn_pix/Res] [get_bd_pins cdc/s_axis_aresetn]
    connect_bd_net [get_bd_pins rstn_pix/Res] [get_bd_pins cdc/m_axis_aresetn]
}
# The display deliberately does NOT follow the link. The scanout runs
# on this board's own 148.5 MHz, and a TV that loses sync every time a
# camera is unplugged is worse than one showing a stale frame: the
# picture path is the board's, the source is the cable's. So the broom,
# not link_rst.
connect_bd_net [get_bd_pins broom/Dout] [get_bd_pins scanout/rst]
# The prover's reset recipe, kept verbatim: rgb2dvi held in reset by
# nothing but the pixel MMCM's own lock.
set lockinv [create_bd_cell -type ip -vlnv xilinx.com:ip:util_vector_logic lock_inv]
set_property -dict [list CONFIG.C_SIZE {1} CONFIG.C_OPERATION {not}] $lockinv
connect_bd_net [get_bd_pins $pixq/locked] [get_bd_pins lock_inv/Op1]
connect_bd_net [get_bd_pins lock_inv/Res] [get_bd_pins hdmi_tx/aRst]
# THE RESET SWEEP: anything a host can reach answers to the board.
# The link's reset (rst_isp/peripheral_aresetn) legitimately resets
# exactly one bus-shaped pin -- the stream converter's island face.
# Every other aresetn the automations parked on it moves to the
# bus's own reset, explicitly. checkhwh audits this from the built
# design; this loop makes the audit boring.
set linknet [get_bd_nets -quiet -of_objects [get_bd_pins rst_isp/peripheral_aresetn]]
if {[llength $linknet]} {
    foreach p [get_bd_pins -quiet -of_objects $linknet] {
        set pn [get_property PATH $p]
        if {[get_property DIR $p] ne "I"} { continue }
        # the ONE legitimate rider: the stream converter's island face
        # flushes with the link (paths carry a leading slash)
        if {$pn eq "/isp_cdc/m_axis_aresetn"} { continue }
        disconnect_bd_net $linknet [get_bd_pins $pn]
        set bn [get_bd_nets -quiet -of_objects [get_bd_pins rst_bus/peripheral_aresetn]]
        if {[llength $bn]} {
            connect_bd_net -net $bn [get_bd_pins $pn]
        } else {
            connect_bd_net [get_bd_pins rst_bus/peripheral_aresetn] [get_bd_pins $pn]
        }
        puts "bd.tcl: reset sweep moved $pn to rst_bus"
    }
}

assign_bd_address
# Explicitly: both stream engines write the DDR through HP0. The
# automation left dma/Data_S2MM UNMAPPED and validate called that a
# warning -- ten builds of silence for want of one segment.
if {$capture} {
    assign_bd_address -target_address_space /dma/Data_S2MM \
        [get_bd_addr_segs ps7/S_AXI_HP0/HP0_DDR_LOWOCM] -force
}
assign_bd_address -target_address_space /vdma/Data_S2MM \
    [get_bd_addr_segs ps7/S_AXI_HP0/HP0_DDR_LOWOCM] -force

validate_bd_design
save_bd_design
make_wrapper -files [get_files rx.bd] -top -import
set_property top rx_wrapper [current_fileset]

puts "BD_DONE"
