#!/usr/bin/env python3
# Copyright 2026 Serge Rabyking
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
"""Audit the BUILT design's clock and reset ancestry, before it is loaded.

The three worst failures on this bench were all wiring the tools accepted
and the board punished: an AXI slave on a clock recovered from the cable
(hung the processor, 2026-08-17); a reset whose polarity the block design
PROPAGATED wrong because nothing declared it (island held in reset while
the link was up); and a bus reset the automation quietly tied to the
link's (three power cycles, 2026-08-18). Every one was convicted in
minutes by READING THE GENERATED DESIGN -- after it had cost a hang.

This runs the reading before the loading. The `.hwh` is the design as
built, not as intended, so this catches what the automation and the
polarity propagation actually did, which `checkbd.py` (the intent-side
check) cannot.

The invariant, learned one power cycle at a time:

    ANYTHING A HOST CAN REACH MUST ANSWER, and that means every clock
    AND every reset on the path from the PS to an addressable slave
    belongs to the BOARD -- never to a cable.

Rules:
  1. Every addressable slave's bus clock has board-only ancestry.
  2. Every addressable slave's bus reset has board-only ancestry --
     nothing on the path derives from link_reset or a cable clock.
  3. The same, for every port of every interconnect: the coupler IS
     the path, and a held coupler hangs exactly like a held slave.
  4. Every proc_sys_reset's ext_reset_in polarity matches its driver:
     an FCLK_RESET*_N source must have C_EXT_RESET_HIGH=0, anything
     else must have it 1 -- "propagated" is how the island came to be
     held in reset precisely while it had work to do.

Ancestry, not name-matching: clocks here are GENERATED by exactly three
kinds of thing -- the PS (board), a clk_wiz (inherits its input), and a
DVI receiver (the cable) -- and resets by the PS, proc_sys_reset
(inherits ext_reset_in), link_reset (the cable, by design), inverters
(inherit), constants (board), and GPIO-driven slices (software: board).
Anything this tracer does not recognise is reported as UNKNOWN and
fails, because an audit that shrugs at what it cannot classify is an
audit that passes the next new failure.

    python3 scripts/checkhwh.py boards/pynq-z2/out/rx.hwh
"""
import pathlib
import re
import sys

BOARD, CABLE, UNKNOWN = "board", "CABLE", "UNKNOWN"


class Design:
    def __init__(self, text: str):
        self.text = text
        # module name -> (modtype, {port: (dir, signame)}, {param: value})
        self.mods = {}
        for m in re.finditer(
                r'<MODULE[^>]*FULLNAME="/([\w/]+)"[^>]*MODTYPE="([\w.]+)"', text):
            name, typ = m.group(1), m.group(2)
            seg = text[m.start():]
            seg = seg[:seg.find("</MODULE>")]
            ports = {p.group(2): (p.group(1), p.group(3)) for p in re.finditer(
                r'<PORT[^>]*DIR="([IO])"[^>]*NAME="([\w\[\]]+)"[^>]*'
                r'SIGNAME="([^"]+)"', seg)}
            # PORT attribute order is not guaranteed; a second pass for
            # the ones the first regex missed.
            for p in re.finditer(r'<PORT ([^>]*)/?>', seg):
                a = p.group(1)
                nm = re.search(r'NAME="([\w\[\]]+)"', a)
                sg = re.search(r'SIGNAME="([^"]+)"', a)
                dr = re.search(r'DIR="([IO])"', a)
                if nm and sg and nm.group(1) not in ports:
                    ports[nm.group(1)] = (dr.group(1) if dr else "?",
                                          sg.group(1))
            params = {p.group(1): p.group(2) for p in re.finditer(
                r'<PARAMETER NAME="([\w]+)" VALUE="([^"]*)"', seg)}
            self.mods[name] = (typ, ports, params)
        # signal -> (module, port) that DRIVES it
        self.driver = {}
        for name, (_typ, ports, _p) in self.mods.items():
            for port, (d, sig) in ports.items():
                if d == "O":
                    self.driver[sig] = (name, port)
        # addressable slaves: whoever owns an ADDRESSBLOCK
        self.slaves = sorted({m.group(1) for m in re.finditer(
            r'FULLNAME="/([\w/]+)"[^>]*IPTYPE="PERIPHERAL"', text)}
            & {n for n, (_t, _po, _pa) in self.mods.items()
               if "<ADDRESSBLOCK" in self._seg(n)})

    def _seg(self, name):
        i = self.text.index(f'FULLNAME="/{name}"')
        seg = self.text[i:]
        return seg[:seg.find("</MODULE>")]

    def sig_of(self, module, port):
        entry = self.mods.get(module)
        if not entry:
            return None
        return entry[1].get(port, (None, None))[1]

    def lineage(self, sig, seen=None):
        """BOARD, CABLE or UNKNOWN for a clock/reset signal."""
        seen = seen or set()
        if sig is None or sig in seen:
            return UNKNOWN
        seen.add(sig)
        drv = self.driver.get(sig)
        if drv is None:
            # driven by nothing inside: an external port -- the cable
            # side of the world (TMDS, HPD...), or a constant net.
            return CABLE if re.search(r"TMDS|hdmi|ddc", sig, re.I) else UNKNOWN
        mod, port = drv
        typ = self.mods[mod][0]
        if "processing_system7" in typ or mod == "ps7":
            return BOARD
        if "clk_wiz" in typ:
            return self.lineage(self.sig_of(mod, "clk_in1"), seen)
        if "dvi2rgb" in typ or "dvi_rx" in mod:
            return CABLE
        if "proc_sys_reset" in typ:
            return self.lineage(self.sig_of(mod, "ext_reset_in"), seen)
        if typ == "link_reset":
            return CABLE          # it exists to relay the cable's state
        if "util_vector_logic" in typ:
            return self.lineage(self.sig_of(mod, "Op1"), seen)
        if "xlconstant" in typ:
            return BOARD
        if "xlslice" in typ:
            return self.lineage(self.sig_of(mod, "Din"), seen)
        if "xlconcat" in typ:
            kids = {self.lineage(self.sig_of(mod, p), set(seen))
                    for p, (d, _s) in self.mods[mod][1].items()
                    if d == "I" and p.startswith("In")}
            if CABLE in kids:
                return CABLE
            return BOARD if kids == {BOARD} else UNKNOWN
        return UNKNOWN


BUS_PIN = re.compile(r"(^|_)(s_axi\w*_?|s_axil_|m\d*_axi_?|lite_)?"
                     r"(aclk|aresetn)$|^(S\d+|M\d+)_(ACLK|ARESETN)$|"
                     r"^(ACLK|ARESETN)$", re.I)


def audit(path: pathlib.Path) -> int:
    d = Design(path.read_text())
    problems = []

    def check_pin(owner, port, sig, what):
        lin = d.lineage(sig)
        if lin is not BOARD:
            problems.append(
                f"{owner}/{port} ({what}) rides {sig!r}, whose ancestry is "
                f"{lin} -- a cable event would stop it answering")

    # Rules 1+2: the addressable slaves' bus pins.
    for slave in d.slaves:
        _typ, ports, _params = d.mods[slave]
        for port, (dr, sig) in ports.items():
            if dr == "I" and BUS_PIN.search(port):
                check_pin(slave, port, sig, "bus pin of an addressable slave")

    # Rule 3: every interconnect port -- the coupler IS the path.
    for name, (typ, ports, _params) in d.mods.items():
        if "axi_interconnect" not in typ:
            continue
        for port, (dr, sig) in ports.items():
            if dr == "I" and re.search(r"(ACLK|ARESETN)$", port):
                check_pin(name, port, sig, "interconnect port")

    # Rule 4: reset polarity is DECLARED-consistent, never propagated
    # into a contradiction.
    for name, (typ, ports, params) in d.mods.items():
        if "proc_sys_reset" not in typ:
            continue
        sig = ports.get("ext_reset_in", (None, None))[1]
        if sig is None:
            continue
        high = params.get("C_EXT_RESET_HIGH")
        wants_low = bool(re.search(r"RESET\d*_N", sig or ""))
        if wants_low and high != "0":
            problems.append(
                f"{name}: ext_reset_in <- {sig} (active-low source) but "
                f"C_EXT_RESET_HIGH={high}")
        if not wants_low and high != "1":
            problems.append(
                f"{name}: ext_reset_in <- {sig} but C_EXT_RESET_HIGH={high} "
                "-- the island-held-in-reset bug is exactly this")

    for problem in problems:
        print(f"  {problem}")
    print(f"  {path.name}: {len(d.slaves)} addressable slaves audited -- "
          f"{'OK' if not problems else f'{len(problems)} problem(s)'}")
    return 1 if problems else 0


def main() -> int:
    targets = [pathlib.Path(a) for a in sys.argv[1:]]
    if not targets:
        here = pathlib.Path(__file__).resolve().parent.parent
        targets = sorted(here.glob("boards/*/out/rx.hwh"))
    if not targets:
        print("  no .hwh to audit")
        return 1
    return max(audit(t) for t in targets)


if __name__ == "__main__":
    sys.exit(main())
