#!/usr/bin/env python3
# Copyright 2026 Serge Rabyking
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
"""The fabric ISP demo: camera to colour, no ARM in the datapath.

blacklevel -> whitebalance -> bilinear demosaic -> rgb_gamma, all
generated by revela/np2hw and running in fabric between the bayerlink
receiver and the framebuffer. The ARM's whole job is this script:
point two VDMA channels at one buffer, flip the mode bit, report.

    python3 isp.py --bit rx.bit
"""
import argparse
import signal
import sys
import json
import time
from pathlib import Path

from pynq import Overlay, allocate, MMIO

MODE_W, MODE_H = 1920, 1080
ISP_W, ISP_H = 1920, 1080   # the TV's best defines the sensor's ask


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bit", default="rx.bit")
    parser.add_argument("--reader", choices=("vdma", "fbread"), default="vdma",
                        help="which engine feeds the display, matching the "
                             "bitstream. vdma is the one that works; fbread "
                             "is right in simulation and does not yet fetch "
                             "a byte on this board")
    parser.add_argument("--skew", type=int, default=0,
                        help="the write engine's data lags its own "
                             "start-of-frame by a number of beats that is "
                             "MEASURED, not derived -- it lands somewhere new "
                             "on every lock. 0 is this bitstream's, checked "
                             "on a screen 2026-08-17; the previous build "
                             "wanted 352, and the same design has wanted 16, "
                             "48 and 80. If the picture is displaced, this is "
                             "the number, and scripts/skew.py moves it live. "
                             "fbread exists to make it not exist")
    parser.add_argument("--interval", type=float, default=10.0,
                        help="heartbeat seconds; changes print immediately "
                             "regardless, so a swap is never missed")
    parser.add_argument("--output", choices=("store", "direct", "both", "off"),
                        default="store",
                        help="which tee branches run: the framebuffer "
                             "store, the direct-to-scanout branch, both, "
                             "or neither (standby -- the pipeline keeps "
                             "running and discards). direct is only whole "
                             "for sources matching the raster's frame "
                             "rate; this bench's Pi does not, so expect "
                             "scanout to refuse between frames")
    parser.add_argument("--seconds", type=float, default=0.0,
                        help="status loop duration; 0 = forever")
    args = parser.parse_args()

    # A plain kill (SIGTERM) must end the loop cleanly: the fabric keeps
    # the picture, and nothing is left needing kill -9.
    signal.signal(signal.SIGTERM, lambda *_: sys.exit(0))

    overlay = Overlay(args.bit, download=True)
    ctrl = MMIO(overlay.ip_dict["ctrl_gpio"]["phys_addr"], 0x1000)
    gpio = MMIO(overlay.ip_dict["status_gpio"]["phys_addr"], 0x1000)
    vdma = MMIO(overlay.ip_dict["vdma"]["phys_addr"], 0x1000)

    # Receiver activity = a header has been ACCEPTED (hdr_valid, bit
    # 27). This used to read a probe bit whose slot the island's
    # status bits now occupy -- and for one build it silently waited
    # on "ISP producing", which is exactly the bit that a held island
    # never raises. A start gate must watch the INPUT side.
    #
    # And it WAITS. The hardware self-heals from any order -- booted
    # with no cable, it parks and comes up the moment a source appears
    # (measured 2026-08-18: lock=0/rst=1 to frames flowing on plug-in,
    # no software touch). A tool that gave up after 30 seconds was the
    # only piece that did not, so "start the board, then plug the
    # camera" only worked if you were quick. The wait is bounded by
    # --seconds like every other wait in this script; it just is not
    # bounded by impatience.
    waited = time.time()
    while not (gpio.read(0) >> 27) & 1:
        if 0 < args.seconds <= time.time() - waited:
            print("no receiver activity within the run's own budget")
            return 2
        if (time.time() - waited) % 30 < 0.5:
            print(f"waiting for a source... ({time.time() - waited:.0f}s, "
                  "plug the camera whenever)")
        time.sleep(0.5)

    # One spare line, kept although the reason for it is gone. It
    # existed because the read started `skew` pixels in and ran that far
    # past the picture; fbread starts exactly at the first pixel and
    # reads exactly MODE_H lines. A line of DDR is a cheap guard against
    # an off-by-one in a fetch engine reading someone else's pages.
    # THREE frames, genlocked, plus the guard row: with two buffers and
    # unrelated frame rates the writer eventually meets the displayed
    # frame -- wait (stall the pipe) or tear. Three is the minimum where
    # neither happens and the reader always shows the newest COMPLETED
    # frame. 25MB against a 128MB CMA pool.
    FSIZE = MODE_H * MODE_W * 4
    fb = allocate(shape=(3 * MODE_H + 1, MODE_W, 4), dtype="u1")
    fb[:] = 16
    fb.flush()

    # Read side, one way or the other.
    if args.reader == "fbread":
        # fbread owns its addressing, so its first beat IS the frame's
        # first pixel of what is IN the buffer. The read-side roll is
        # gone -- and its absence decomposed the old measurement: the
        # single --skew was always the SUM of two rolls, and the
        # WRITE engine's half remains (the VDMA s2mm lands frames at
        # a per-lock offset; 48 px measured 2026-08-19, from the
        # same 0/16/48/80 family as ever). So --skew survives here,
        # applied to the base address, until #32's fbwrite owns the
        # write side the way fbread now owns the read.
        ctrl.write(0x8, fb.physical_address + args.skew * 4)
    else:
        # The VDMA's data lags its own start-of-frame marker by a number
        # that lands somewhere new on every lock. Start the read that far
        # in. Measured per bitstream with ruler.py and a capture card.
        # GenlockEn (bit3) + internal GenlockSrc (bit7): the read side
        # follows the write side's frame pointer inside the core, one
        # completed frame behind. A propagated fsync+slave with nothing
        # driving the pointer once starved this engine forever, so the
        # pointer source is INTERNAL, on purpose, in software's hand.
        vdma.write(0x00, 0x3 | (1 << 3) | (1 << 7))
        for n in range(3):
            vdma.write(0x5C + 4 * n,
                       fb.physical_address + n * FSIZE + args.skew * 4)
        vdma.write(0x58, MODE_W * 4)
        vdma.write(0x54, MODE_W * 4)
        vdma.write(0x50, MODE_H)

    # Write side: the ISP lands its window centred, forever.
    x0 = (MODE_W - ISP_W) // 2
    y0 = (MODE_H - ISP_H) // 2
    base = fb.physical_address + (y0 * MODE_W + x0) * 4
    vdma.write(0x30, 0x3 | (1 << 3) | (1 << 7))
    for n in range(3):
        vdma.write(0xAC + 4 * n, base + n * FSIZE)
    vdma.write(0xA8, MODE_W * 4)                # stride
    vdma.write(0xA4, ISP_W * 4)                 # hsize
    vdma.write(0xA0, ISP_H)                     # vsize -> go

    # Only now flip the stream into the armed S2MM, so the first frame
    # it ever sees starts at a tuser boundary.  Bit1 = consumer, bit0 =
    # broom; the broom sweeps while ISP mode is held.
    # Base control word: consumer select (bit1) plus the tee enables --
    # store (bit3) and direct (bit4). The tee honours changes at frame
    # boundaries only, so these flip whole frames, never mid-frame.
    tee_bits = {"store": 0x8, "direct": 0x10, "both": 0x18, "off": 0x0}
    cbase = 0x2 | tee_bits[args.output]
    ctrl.write(0, cbase | 1)
    time.sleep(0.05)
    ctrl.write(0, cbase)
    # ADDRESS FIRST, THEN ENABLE, and not the other way round: those 32
    # bits cross into the display clock without a synchroniser because
    # they are still by the time they matter, and enable rising is what
    # says they are. Bit 2 alongside the consumer select.
    if args.reader == "fbread":
        # ADDRESS FIRST, THEN ENABLE: those 32 bits cross into the
        # display clock without a synchroniser because they are still by
        # the time they matter, and enable rising says they are.
        time.sleep(0.01)
        ctrl.write(0, cbase | 0x4)

        # THE ROTATION, in software until #32 publishes it in fabric:
        # fbread must read the buffer the writer FINISHED LAST, never
        # the one being written -- a fixed base met the cycling writer
        # once per three frames, a 10 Hz flicker photographed
        # 2026-08-19. The s2mm's PARK_PTR register says which store
        # it is writing NOW (bits 28:24); last completed is one
        # behind. fbread samples base_addr at each frame restart, so
        # a mid-frame write here lands cleanly on the next frame.
        # A 5 ms poll is three chances per source frame -- and this
        # thread is exactly the kind of software-in-the-loop that
        # #32's fbwrite exists to retire, labelled as such.
        import os
        import threading

        def follow_writer():
            last = -1
            while True:
                wr = (vdma.read(0x28) >> 24) & 0x1F
                done = (wr + 2) % 3
                if done != last:
                    ctrl.write(0x8,
                               fb.physical_address + done * FSIZE
                               + args.skew * 4)
                    last = done
                time.sleep(0.005)
        if os.environ.get("FB_FOLLOW", "1") == "1":
            threading.Thread(target=follow_writer, daemon=True).start()
        else:
            print("fbread: follower OFF (FB_FOLLOW=0) -- fixed base, "
                  "for experiments that must not restart the engine")
    time.sleep(0.1)

    hgpio = MMIO(overlay.ip_dict["hdr_gpio"]["phys_addr"], 0x1000)
    heals = [0]

    # A CONTROL build boots NEUTRAL -- gains 1.0, identity matrix --
    # which on this sensor is a green picture with no red. That is
    # correct hardware behaviour and wrong bench behaviour: real
    # software loads the calibration, so this does. Both files sit
    # beside this script; the map answers where, the defaults what.
    # ("red is absent" -- 2026-08-18, and it was wb.gain_0_0 at 256
    # where the calibration wanted 412.)
    map_p = Path(__file__).parent / "revela_isp.regmap.json"
    def_p = Path(__file__).parent / "revela_isp.defaults.json"
    if "isp" in overlay.ip_dict and map_p.exists() and def_p.exists():
        rmap = json.loads(map_p.read_text())
        base = overlay.ip_dict["isp"]["phys_addr"]
        csr = MMIO(base, 1 << rmap["control"]["address_bits"])
        addr = {f"{b['path']}.{r['name']}": (r["address"], r["bits"])
                for b in rmap["blocks"] for r in b["registers"]}
        for key, val in json.loads(def_p.read_text()).items():
            if key in addr:
                a, bits = addr[key]
                csr.write(a, (val + (1 << bits)) % (1 << bits))
        csr.write(addr["pipe.commit"][0], 1)
        deadline = time.time() + 1.0
        while (csr.read(addr["pipe.commit"][0]) & 1) and time.time() < deadline:
            time.sleep(0.005)
        state = "applied" if not (csr.read(addr["pipe.commit"][0]) & 1) \
            else "PENDING (no frames yet; lands at the first boundary)"
        print(f"calibration: {state}")

    def identity():
        """(source, resyncs, link up, drops) -- the one word a swap moves."""
        w = hgpio.read(0x8)
        return (w & 0xFF, (w >> 8) & 0xFF, (w >> 16) & 1, (w >> 17) & 0xFF)

    def report(tag):
        s1 = gpio.read(0)
        s2 = gpio.read(0x8)
        # The stream's identity and the link's health, one word:
        # {loss[7:0], up, resyncs[7:0], source[7:0]}. Counts, not flags,
        # so a poll that misses an event still sees that it happened.
        seq = hgpio.read(0)
        idw = hgpio.read(0x8)
        src, resyncs = idw & 0xFF, (idw >> 8) & 0xFF
        up, losses = (idw >> 16) & 1, (idw >> 17) & 0xFF
        fb_under, fb_err = (idw >> 25) & 1, (idw >> 26) & 1
        dbg = (idw >> 27) & 0x1F   # run,acct,short,stalled,long
        # AUTO-HEAL, labelled as the patch it is: the engine can
        # stall with its books pinned (acct latches the violation
        # class -- arrivals exceeding bookings, mechanism still
        # under investigation). Enable-rise is a full clean restart
        # in fabric now, so the heal is one toggle. Every heal is
        # COUNTED and printed: a silent workaround would bury the
        # evidence the root cause needs.
        # heal on FAULT STICKIES only. 'stalled' fires whenever the
        # prefetch FIFO is comfortably full -- which is HEALTH -- and
        # a heal triggered on it executed a working engine once per
        # heartbeat for an evening. acct/short/long latch only on a
        # real protocol violation.
        if args.reader == "fbread" and (dbg & 0b10110):
            heals[0] += 1
            cur = ctrl.read(0)
            ctrl.write(0, cur & ~0x4)
            time.sleep(0.002)
            ctrl.write(0, cur | 0x4)
            print(f"fbread HEALED (#{heals[0]}): stalled=1, "
                  f"acct={(dbg >> 2) & 1} -- books reset by enable rise")
        hdr = s1 >> 18
        # scanout's status word: sof-per-frame[2:0], locked, armed,
        # underflow, misalign, refused. Exactly one start-of-frame beat
        # per frame is correct; anything else means the stream's framing
        # is not what the raster is anchoring to.
        sc = (s2 >> 17) & 0x7FFF
        # The island's six levels -- see isl_cat in bd.tcl.
        isl = (s1 >> 2) & 0x3F
        print(f"{tag}: lock={s1 & 1} ovf={(s1 >> 1) & 1} "
              f"isl[rst={isl & 1} inV={(isl >> 1) & 1} inR={(isl >> 2) & 1} "
              f"outV={(isl >> 3) & 1} shV={(isl >> 4) & 1} "
              f"shR={(isl >> 5) & 1}] "
              f"refused={hdr & 1} bits={(hdr >> 4) & 0x1F} | scanout "
              f"armed={(sc >> 4) & 1} under={(sc >> 5) & 1} "
              f"misalign={(sc >> 6) & 1} win_refused={(sc >> 7) & 1} "
              f"sof/frame={sc & 7} | "
              f"s2mm_sr={vdma.read(0x34):#x} mm2s_sr={vdma.read(0x04):#x} | "
              f"src={src} frame={seq} link={'up' if up else 'DOWN'} "
              f"drops={losses} resyncs={resyncs} "
              f"fb_under={fb_under} fb_err={fb_err} "
              f"fb[run={dbg & 1} acct={(dbg >> 1) & 1} "
              f"short={(dbg >> 2) & 1} stalled={(dbg >> 3) & 1} "
              f"long={(dbg >> 4) & 1}]")

    report("up")
    t0 = time.time()
    # Poll the identity word FAST and print when it moves. A hot swap is
    # over in well under a second: on a ten-second heartbeat the unplug,
    # the recovery and the new sensor all land in one line, which is the
    # same as not seeing them.
    last = identity()
    beat = t0
    unhalts, unhalt_t = 0, 0.0
    try:
        while args.seconds <= 0 or time.time() - t0 < args.seconds:
            time.sleep(0.05)
            now = identity()
            if now != last:
                src, res, up, drops = now
                report(f"t+{time.time() - t0:4.0f}s CHANGE "
                       f"link={'up' if up else 'DOWN'} src={src} "
                       f"drops={drops} resyncs={res}")
                last = now
            if time.time() - beat >= args.interval:
                beat = time.time()
                report(f"t+{time.time() - t0:4.0f}s")
            # SUPERVISOR, and labelled a patch: a VDMA that halts on a
            # framing hiccup (SOFLateErr at a mid-frame unplug) never
            # restarts itself, so the link would heal and the picture
            # would stay frozen forever. The real fix retires the
            # engine (#20/#39); until then a halted writer is cleared
            # and re-armed -- only while the link is up, at most once a
            # second, and COUNTED, because a restart happening often
            # enough to matter is a bug report, not a recovery.
            if (args.reader == "vdma" and time.time() - unhalt_t > 1.0
                    and now[2] and args.output in ("store", "both")):
                sr = vdma.read(0x34)
                if sr & 1:                             # Halted
                    vdma.write(0x34, sr)               # W1C the stickies
                    vdma.write(0x30, 0x3)              # run, circular
                    vdma.write(0xA8, MODE_W * 4)
                    vdma.write(0xA4, ISP_W * 4)
                    vdma.write(0xA0, ISP_H)            # vsize -> go
                    unhalts += 1
                    unhalt_t = time.time()
                    report(f"t+{time.time() - t0:4.0f}s UNHALT #{unhalts} "
                           f"(s2mm was 0x{sr:08x})")
    except KeyboardInterrupt:
        pass
    finally:
        # The process's exit frees the CMA framebuffer, so the WRITER
        # must not outlive it: an S2MM left running scribbles 60 frames
        # a second over whatever the kernel hands those pages to next --
        # page cache included, which is how an SD card's rootfs rots.
        # The read side may keep scanning out; reads hurt nobody.
        vdma.write(0x30, 0x0)
        # And stop the READ engine the same way it was started: with no
        # base address there is nothing to fetch. It must not outlive
        # this process either -- the pages go back to the kernel when
        # the buffer is freed, and a master still reading them is a
        # master reading whatever they become next.
        if args.reader == "fbread":
            ctrl.write(0, ctrl.read(0) & ~0x4)   # stop fetching
            ctrl.write(0x8, 0)
        time.sleep(0.05)
    return 0


if __name__ == "__main__":
    sys.exit(main())
