#!/usr/bin/env python3
# Copyright 2026 Serge Rabyking
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
"""The fabric ISP demo: camera to colour, no ARM in the datapath.

blacklevel -> whitebalance -> bilinear demosaic -> rgb_gamma, all
generated by revela/np2hw and running in fabric between the bayerlink
receiver and the framebuffer. The ARM's whole job is this script:
point two VDMA channels at one buffer, flip the mode bit, report.

    python3 isp.py --bit rx.bit
"""
import argparse
import sys
import time

from pynq import Overlay, allocate, MMIO

MODE_W, MODE_H = 1280, 720
ISP_W, ISP_H = 512, 240


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bit", default="rx.bit")
    parser.add_argument("--seconds", type=float, default=600.0)
    args = parser.parse_args()

    overlay = Overlay(args.bit, download=True)
    ctrl = MMIO(overlay.ip_dict["ctrl_gpio"]["phys_addr"], 0x1000)
    gpio = MMIO(overlay.ip_dict["status_gpio"]["phys_addr"], 0x1000)
    vdma = MMIO(overlay.ip_dict["vdma"]["phys_addr"], 0x1000)

    for _ in range(60):
        if (gpio.read(0) >> 5) & 1:
            break
        time.sleep(0.5)
    else:
        print("no receiver activity: is the source streaming?")
        return 2

    # ISP mode held while the broom sweeps: bit1 = consumer, bit0 = broom.
    ctrl.write(0, 0x3)
    time.sleep(0.05)
    ctrl.write(0, 0x2)
    time.sleep(0.1)

    fb = allocate(shape=(MODE_H, MODE_W, 4), dtype="u1")
    fb[:] = 16
    fb.flush()

    # Read side: the raster scans the whole frame, forever.
    vdma.write(0x00, 0x3)
    for n in range(3):
        vdma.write(0x5C + 4 * n, fb.physical_address)
    vdma.write(0x58, MODE_W * 4)
    vdma.write(0x54, MODE_W * 4)
    vdma.write(0x50, MODE_H)

    # Write side: the ISP lands its window centred, forever.
    x0 = (MODE_W - ISP_W) // 2
    y0 = (MODE_H - ISP_H) // 2
    base = fb.physical_address + (y0 * MODE_W + x0) * 4
    vdma.write(0x30, 0x3)
    for n in range(3):
        vdma.write(0xAC + 4 * n, base)
    vdma.write(0xA8, MODE_W * 4)                # stride
    vdma.write(0xA4, ISP_W * 4)                 # hsize
    vdma.write(0xA0, ISP_H)                     # vsize -> go

    def report(tag):
        s1 = gpio.read(0)
        s2 = gpio.read(0x8)
        hdr = s1 >> 18
        print(f"{tag}: lock={s1 & 1} ovf={(s1 >> 1) & 1} "
              f"refused={hdr & 1} bits={(hdr >> 4) & 0x1F} "
              f"tx_aligned={(s2 >> 22) & 1} "
              f"s2mm_sr={vdma.read(0x34):#x} mm2s_sr={vdma.read(0x04):#x}")

    report("up")
    t0 = time.time()
    while time.time() - t0 < args.seconds:
        time.sleep(10)
        report(f"t+{time.time() - t0:4.0f}s")
    return 0


if __name__ == "__main__":
    sys.exit(main())
