#!/usr/bin/env python3
# Copyright 2026 Serge Rabyking
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
"""The fabric ISP demo: camera to colour, no ARM in the datapath.

blacklevel -> whitebalance -> bilinear demosaic -> rgb_gamma, all
generated by revela/np2hw and running in fabric between the bayerlink
receiver and the framebuffer. The ARM's whole job is this script:
point two VDMA channels at one buffer, flip the mode bit, report.

    python3 isp.py --bit rx.bit
"""
import argparse
import signal
import sys
import time

from pynq import Overlay, allocate, MMIO

MODE_W, MODE_H = 1920, 1080
ISP_W, ISP_H = 1920, 1080   # the TV's best defines the sensor's ask


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bit", default="rx.bit")
    parser.add_argument("--reader", choices=("vdma", "fbread"), default="vdma",
                        help="which engine feeds the display, matching the "
                             "bitstream. vdma is the one that works; fbread "
                             "is right in simulation and does not yet fetch "
                             "a byte on this board")
    parser.add_argument("--skew", type=int, default=0,
                        help="vdma only: the read engine's data lags its own "
                             "start-of-frame by a number of beats that is "
                             "MEASURED, not derived -- it lands somewhere new "
                             "on every lock. 0 is this bitstream's, checked "
                             "on a screen 2026-08-17; the previous build "
                             "wanted 352, and the same design has wanted 16, "
                             "48 and 80. If the picture is displaced, this is "
                             "the number, and scripts/skew.py moves it live. "
                             "fbread exists to make it not exist")
    parser.add_argument("--interval", type=float, default=10.0,
                        help="heartbeat seconds; changes print immediately "
                             "regardless, so a swap is never missed")
    parser.add_argument("--seconds", type=float, default=0.0,
                        help="status loop duration; 0 = forever")
    args = parser.parse_args()

    # A plain kill (SIGTERM) must end the loop cleanly: the fabric keeps
    # the picture, and nothing is left needing kill -9.
    signal.signal(signal.SIGTERM, lambda *_: sys.exit(0))

    overlay = Overlay(args.bit, download=True)
    ctrl = MMIO(overlay.ip_dict["ctrl_gpio"]["phys_addr"], 0x1000)
    gpio = MMIO(overlay.ip_dict["status_gpio"]["phys_addr"], 0x1000)
    vdma = MMIO(overlay.ip_dict["vdma"]["phys_addr"], 0x1000)

    for _ in range(60):
        if (gpio.read(0) >> 5) & 1:
            break
        time.sleep(0.5)
    else:
        print("no receiver activity: is the source streaming?")
        return 2

    # One spare line, kept although the reason for it is gone. It
    # existed because the read started `skew` pixels in and ran that far
    # past the picture; fbread starts exactly at the first pixel and
    # reads exactly MODE_H lines. A line of DDR is a cheap guard against
    # an off-by-one in a fetch engine reading someone else's pages.
    fb = allocate(shape=(MODE_H + 1, MODE_W, 4), dtype="u1")
    fb[:] = 16
    fb.flush()

    # Read side, one way or the other.
    if args.reader == "fbread":
        # fbread owns its addressing, so its first beat IS the frame's
        # first pixel: no offset to measure, no --skew to carry. Only
        # WHERE Linux put the buffer can be known here.
        ctrl.write(0x8, fb.physical_address)
    else:
        # The VDMA's data lags its own start-of-frame marker by a number
        # that lands somewhere new on every lock. Start the read that far
        # in. Measured per bitstream with ruler.py and a capture card.
        vdma.write(0x00, 0x3)
        for n in range(3):
            vdma.write(0x5C + 4 * n, fb.physical_address + args.skew * 4)
        vdma.write(0x58, MODE_W * 4)
        vdma.write(0x54, MODE_W * 4)
        vdma.write(0x50, MODE_H)

    # Write side: the ISP lands its window centred, forever.
    x0 = (MODE_W - ISP_W) // 2
    y0 = (MODE_H - ISP_H) // 2
    base = fb.physical_address + (y0 * MODE_W + x0) * 4
    vdma.write(0x30, 0x3)
    for n in range(3):
        vdma.write(0xAC + 4 * n, base)
    vdma.write(0xA8, MODE_W * 4)                # stride
    vdma.write(0xA4, ISP_W * 4)                 # hsize
    vdma.write(0xA0, ISP_H)                     # vsize -> go

    # Only now flip the stream into the armed S2MM, so the first frame
    # it ever sees starts at a tuser boundary.  Bit1 = consumer, bit0 =
    # broom; the broom sweeps while ISP mode is held.
    ctrl.write(0, 0x3)
    time.sleep(0.05)
    ctrl.write(0, 0x2)
    # ADDRESS FIRST, THEN ENABLE, and not the other way round: those 32
    # bits cross into the display clock without a synchroniser because
    # they are still by the time they matter, and enable rising is what
    # says they are. Bit 2 alongside the consumer select.
    if args.reader == "fbread":
        # ADDRESS FIRST, THEN ENABLE: those 32 bits cross into the
        # display clock without a synchroniser because they are still by
        # the time they matter, and enable rising says they are.
        time.sleep(0.01)
        ctrl.write(0, 0x6)
    time.sleep(0.1)

    hgpio = MMIO(overlay.ip_dict["hdr_gpio"]["phys_addr"], 0x1000)

    def identity():
        """(source, resyncs, link up, drops) -- the one word a swap moves."""
        w = hgpio.read(0x8)
        return (w & 0xFF, (w >> 8) & 0xFF, (w >> 16) & 1, (w >> 17) & 0xFF)

    def report(tag):
        s1 = gpio.read(0)
        s2 = gpio.read(0x8)
        # The stream's identity and the link's health, one word:
        # {loss[7:0], up, resyncs[7:0], source[7:0]}. Counts, not flags,
        # so a poll that misses an event still sees that it happened.
        seq = hgpio.read(0)
        idw = hgpio.read(0x8)
        src, resyncs = idw & 0xFF, (idw >> 8) & 0xFF
        up, losses = (idw >> 16) & 1, (idw >> 17) & 0xFF
        fb_under, fb_err = (idw >> 25) & 1, (idw >> 26) & 1
        dbg = (idw >> 27) & 0x1F   # run,en,arvalid,started,under
        hdr = s1 >> 18
        # scanout's status word: sof-per-frame[2:0], locked, armed,
        # underflow, misalign, refused. Exactly one start-of-frame beat
        # per frame is correct; anything else means the stream's framing
        # is not what the raster is anchoring to.
        sc = (s2 >> 17) & 0x7FFF
        print(f"{tag}: lock={s1 & 1} ovf={(s1 >> 1) & 1} "
              f"refused={hdr & 1} bits={(hdr >> 4) & 0x1F} | scanout "
              f"armed={(sc >> 4) & 1} under={(sc >> 5) & 1} "
              f"misalign={(sc >> 6) & 1} win_refused={(sc >> 7) & 1} "
              f"sof/frame={sc & 7} | "
              f"s2mm_sr={vdma.read(0x34):#x} mm2s_sr={vdma.read(0x04):#x} | "
              f"src={src} frame={seq} link={'up' if up else 'DOWN'} "
              f"drops={losses} resyncs={resyncs} "
              f"fb_under={fb_under} fb_err={fb_err} "
              f"fb[run={dbg & 1} en={(dbg >> 1) & 1} "
              f"arvalid={(dbg >> 2) & 1} started={(dbg >> 3) & 1}]")

    report("up")
    t0 = time.time()
    # Poll the identity word FAST and print when it moves. A hot swap is
    # over in well under a second: on a ten-second heartbeat the unplug,
    # the recovery and the new sensor all land in one line, which is the
    # same as not seeing them.
    last = identity()
    beat = t0
    try:
        while args.seconds <= 0 or time.time() - t0 < args.seconds:
            time.sleep(0.05)
            now = identity()
            if now != last:
                src, res, up, drops = now
                report(f"t+{time.time() - t0:4.0f}s CHANGE "
                       f"link={'up' if up else 'DOWN'} src={src} "
                       f"drops={drops} resyncs={res}")
                last = now
            if time.time() - beat >= args.interval:
                beat = time.time()
                report(f"t+{time.time() - t0:4.0f}s")
    except KeyboardInterrupt:
        pass
    finally:
        # The process's exit frees the CMA framebuffer, so the WRITER
        # must not outlive it: an S2MM left running scribbles 60 frames
        # a second over whatever the kernel hands those pages to next --
        # page cache included, which is how an SD card's rootfs rots.
        # The read side may keep scanning out; reads hurt nobody.
        vdma.write(0x30, 0x0)
        # And stop the READ engine the same way it was started: with no
        # base address there is nothing to fetch. It must not outlive
        # this process either -- the pages go back to the kernel when
        # the buffer is freed, and a master still reading them is a
        # master reading whatever they become next.
        if args.reader == "fbread":
            ctrl.write(0, ctrl.read(0) & ~0x4)   # stop fetching
            ctrl.write(0x8, 0)
        time.sleep(0.05)
    return 0


if __name__ == "__main__":
    sys.exit(main())
